// <auto-generated />
namespace AdSystem.MVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class user_details_changed : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(user_details_changed));
        
        string IMigrationMetadata.Id
        {
            get { return "201807010903239_user_details_changed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
